/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appSurveyRouteImport } from './routes/(app)/survey'

const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appSurveyRoute = appSurveyRouteImport.update({
  id: '/(app)/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/survey': typeof appSurveyRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesByTo {
  '/survey': typeof appSurveyRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/survey': typeof appSurveyRoute
  '/(auth)/login': typeof authLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/survey' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/survey' | '/login'
  id: '__root__' | '/(app)/survey' | '/(auth)/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appSurveyRoute: typeof appSurveyRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/survey': {
      id: '/(app)/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof appSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appSurveyRoute: appSurveyRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
